version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dynamo-es-sync"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xe2nd9sec21l"
s3_prefix = "dynamo-es-sync"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
